openapi: 3.0.1
info:
  title: Library Management API
  version: 1.0.0
  description: API for managing a library system including books, members, rented books, and transactions.

servers:
  - url: http://localhost:5000

paths:
  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    post:
      summary: Add or update a book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                book_id:
                  type: integer
                quantity:
                  type: integer
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    delete:
      summary: Delete a book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                book_id:
                  type: integer
                quantity:
                  type: integer
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /members:
    get:
      summary: Get all members
      responses:
        '200':
          description: A list of members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Member'

    post:
      summary: Create a new member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Member created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  member_id:
                    type: integer

    delete:
      summary: Delete a member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                member_id:
                  type: integer
      responses:
        '200':
          description: Member deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /rent:
    post:
      summary: Rent books
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  member_id:
                    type: integer
                  rented_books:
                    type: array
                    items:
                      type: object
                      properties:
                        book_id:
                          type: integer
                        quantity:
                          type: integer
      responses:
        '201':
          description: Books rented successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    delete:
      summary: Return rented books
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  member_id:
                    type: integer
                  rented_books:
                    type: array
                    items:
                      type: object
                      properties:
                        book_id:
                          type: integer
                        quantity:
                          type: integer
      responses:
        '200':
          description: Books returned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    get:
      summary: Get all rented books
      responses:
        '200':
          description: A list of rented books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RentedBook'

  /transactions:
    get:
      summary: Get all transactions
      responses:
        '200':
          description: A list of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'

components:
  schemas:
    Book:
      type: object
      properties:
        book_id:
          type: integer
        quantity:
          type: integer

    Member:
      type: object
      properties:
        member_id:
          type: integer
        name:
          type: string
        debt:
          type: number

    RentedBook:
      type: object
      properties:
        id:
          type: integer
        book_id:
          type: integer
        member_id:
          type: integer
        quantity:
          type: integer

    Transaction:
      type: object
      properties:
        id:
          type: integer
        book_id:
          type: integer
        member_id:
          type: integer
        quantity:
          type: integer
        action:
          type: string
